image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo -D -d public --config config-gitlab.toml
  artifacts:
    paths:
    - public
  only:
  - master
