theme = "hugo-icon"
baseURL = "https://erlang-connection.eu"
languageCode = "en-US"
title = "Erlang Connection"

[params]
  author = "Erlang Connection"
  description = "Free and open Erlang Connection organization"

[params.hero]
  img = "images/hero_bg.jpg"
  title = "Erlang Connection"
  description = "An open and collaborative European platform for a sustainable Erlang ecosystem"

# Navigation section
[params.nav]
  mission = "Our Mission"
  services = "Services"
  team = "The Team"
  contact = "Get In Touch"

[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "learn"
    title = "Learn"
    subtitle = "A new way of thinking and doing with Erlang"
    description = "Erlang is a functional and distributed programming language based on modern concept. This uncommon paradigm can be complex to understand. We are here to help you to progress."

  [[params.mission.item]]
    weight = 2
    name = "share"
    title = "Share"
    subtitle = "Our vision to the IT world"
    description = "Erlang Connection is a free and open organization. We want to create a platform where people can share and exchange about their experiences and usage in Erlang. Get all you need to succeed with Erlang."

  [[params.mission.item]]
    weight = 3
    name = "meet"
    title = "Meet"
    subtitle = "The active members of the community"
    description = "Erlang is an open-source language, with a large community of different profile. We want to give you the possibility to meet them, from social events to mentoring."

# Services section
[params.services]
  enable = true
  # add video in a near future
  # video = false 
  # vidlink = ""
  title = "Our Services (coming soon)"
  description = "Become a member, and access to a large community of Erlang professional using this language day to day."

  [[params.services.item]]
    icon = "icon-book"
    title = "Erlang Touch (soon)"
    description = "With Erlang Touch stay in contact with users, developers and companies using Erlang in their day to day activities."

  [[params.services.item]]
    icon = "icon-group"
    title = "Erlang Punch (soon)"
    description = "Mentors and mentees can meet on the platform to learn about the languages and programs based on Erlang."

  [[params.services.item]]
    icon = "icon-paper-plane (soon)"
    title = "Erlang Connect"
    description = "Conferences, meetups, or social events to see each other, in Europe."

# Work section
[params.work]
  enable = true
 
  [[params.work.item]]
    title = "Organization Statuts"
    subtitle = "Like any free and open organization, you should have access to the statuts"
    target = "/doc/statuts.pdf"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Organization Rules"
    subtitle = "Organization rules extend the statuts by defining how it works"
    img = "images/img_3.jpg"
    target = "/doc/reglement-interieur.pdf"

  [[params.work.item]]
    title = "Subscribe"
    subtitle = "Come and join us!"
    img = "images/img_2.jpg"
    target = "https://www.helloasso.com/associations/erlang-connection/adhesions/adhesion"
 
  [[params.work.item]]
    title = "Documentation"
    subtitle = "Here our official documentation for our speakers."
    img = "images/img_3.jpg"
    target = "https://erlang-connection.eu/doc/speakers.pdf"
 
  [[params.work.item]]
    title = "Github"
    subtitle = "Our official github account"
    img = "images/img_3.jpg"
    target = "https://github.com/erlang-connection"
 
  [[params.work.item]]
    title = "Meet us with Jitsi "
    subtitle = "Our official and dedicated Jitsi platform"
    img = "images/img_2.jpg"
    target = "https://meet.erlang-connect.eu/"
 
  [[params.work.item]]
    title = "Twitch"
    subtitle = "Here our main streaming solution"
    img = "images/img_3.jpg"
    target = "https://www.twitch.tv/erlangconnection"
 
  [[params.work.item]]
    title = "LinkedIn"
    subtitle = "Web Design"
    img = "images/img_4.jpg"
    target = "https://www.linkedin.com/groups/12384661/"

# Team section
[params.team]
  enable = true
  title = "Meet The Team"
  description = "Made by passionate to everyone. Our team is here to help you reaching your goals and answers your questions. Contact them, they will be happy"

  [[params.team.item]]
    name = "Benoît Chesneau"
    img = "img/benoit.jpg"
    position = "President (co-founder)"
    description = "Benoit Chesneau is the founder of Enki Multimedia, a company providing P2P and data solutions and consulting. He has 14 years of experience in Erlang and is the author of many opensource libraries and projects. He is also the author of Gunicorn a well known WSGI server written in Python."
    twitter = "https://twitter.com/benoitc"
    github = "https://github.com/benoitc"

  [[params.team.item]]
    name = "Mathieu Kerjouan"
    position = "Secretary (co-founder)"
    description = "Sysadmin and System Architect. Felt in love with functional programming many years ago. Use OpenBSD and Erlang in day to day activities. Like to share its knowledge and organize events in France and Europe."
    img = "img/mathieu.jpg"
    twitter = "https://twitter.com/niamtokik"
    github = "https://github.com/niamtokik"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "If you want to have more information and news about Erlang Connection, you can fill [this form hosted on framaforms servers](https://framaforms.org/information-erlang-connection-1586269396)."
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"
  form = false

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = ""
  github = "https://github.com/erlang-connection"
  twitter = "https://twitter.com/ErlangConnect"
  linkedin = "https://www.linkedin.com/groups/12384661/"
  # instagram = "#"
  
